services:
    phpbb.teamsecurity.listener:
        class: phpbb\teamsecurity\event\listener
        arguments:
            - '@config'
            - '@messenger.method.email'
            - '@language'
            - '@log'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
